// Re-export all Zod schemas from the generated API spec
export * from "./generated/api";

// Re-export type helpers from generated types, excluding names that collide with Zod schemas
// (Orval generates both a Zod schema AND a type with the same name for request bodies)
export type {
  HealthStatus,
  StatusResponse,
  ErrorResponse,
  PaginationMeta,
  AuthResponse,
  User,
  UserRole,
  CreateUserRequestRole,
  UserUpdateRole,
  Department,
  DepartmentUpdate,
  ChecklistTemplate,
  ChecklistTemplateInput,
  ExitCase,
  ExitCaseStatus,
  ExitCaseWithRelations,
  CreateCaseRequest,
  CaseComment,
  CaseCommentVisibility,
  AddCommentRequest,
  AddCommentRequestVisibility,
  ClearanceTask,
  ClearanceTaskStatus,
  ClearanceTaskWithCase,
  ChecklistItem,
  ChecklistItemInput,
  TimelineEvent,
  ExitInterview,
  ExitInterviewRequest,
  ExitInterviewResponse,
  Document,
  DocumentDocType,
  Notification,
  NotificationType,
  NotificationPreferencesResponse,
  NotificationPreferencesUpdate,
  AuditLogEntry,
  AuditLogEntryType,
  PaginatedAuditLogs,
  WorkflowConfig,
  WorkflowConfigInput,
  WorkflowConfigUpdate,
  ExitTrendsResponse,
  ExitTrendsResponseDataItem,
  ExitReasonsResponse,
  ExitReasonsResponseDataItem,
  TurnaroundResponse,
  TurnaroundResponseDataItem,
  SLAPerformanceResponse,
  SLAPerformanceResponseDataItem,
  LoginRequest,
  ListCasesParams,
  ListTasksParams,
  ListNotificationsParams,
  ListAuditLogsParams,
  GetExitTrendsParams,
  GetSLAPerformanceParams,
  ExportAuditLogsParams,
  UploadDocumentBodyDocType,
  GenerateDocumentBodyDocType,
} from "./generated/types";
